# Site settings
description: A blog about discovering through data
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://awesomestats.in" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Manaranjan Pradhan
user_description: A data enthusiast
user_title: Awesomestats
email: manaranjan@enablecloud.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Spark
    url: /spark
  - title: Python
    url: /python
  - title: Stats
    url: /stats
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
