# Site settings
description: A blog about discovering through data
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.awesomestats.in" # the base hostname & protocol for your site

# User settings
username: Manaranjan Pradhan
user_description: A data enthusiast
user_title: Awesomestats
email: manaranjan@enablecloud.com
twitter_username: manaranjanp
github_username:  manaranjanp
gplus_username:  manaranjan
disqus_username: manaranjanpradhan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Google Analytics Tracking ID
google_analytics: UA-78444977-1

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Spark
    url: /spark
  - title: Python
    url: /python
  - title: Amazing Stats
    url: /amazing
  - title: Workshops
    url: /workshops    
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-minimal